### ISSUE TITLE
still using Debian 11?

### ISSUE THREAD

**Issue by nutterthanos** [CNMan/C2R#2]
Are you still using Debian 11 and what versions of packages are used in the script? since im currently got it running in Github Actions with ubuntu-latest on a fork but it seems to not work properly where it would mark the dates with stat as current date/time to the README.md and not the date/time its meant to set and it would not update the files in the officecdn.microsoft.com folder even if there was an actual update sometimes.

**Comment by CNMan** [comment]
Running on latest Debian 12
```
apt-get -y install cabextract
```

**Comment by nutterthanos** [comment]
k
