### ISSUE TITLE
PerpetualVL2024 

### ISSUE THREAD

**Issue by iDolmatov** [CNMan/C2R#3]
Channels are already in the official API inside OfficeC2RClient, but not in the table.

```
Insiders_LTSC2024: 20481F5C-C268-4624-936C-52EB39DDBD97
Microsoft_LTSC2024: C02D8FE6-5242-4DA8-972F-82EE55E00671
Production_LTSC2024: 7983BAC0-E531-40CF-BE00-FD24FE66619C
```

https://mrodevicemgr.officeapps.live.com/mrodevicemgrsvc/api/v2/C2RReleaseData
`    "Id": 1170263,
    "Name": "Default",
    "Order": 100,
    "FFN": "7983bac0-e531-40cf-be00-fd24fe66619c",
    "AvailableBuild": "16.0.17425.20000",
    "ThrottleLevel": 0,
    "LkgBuild": "16.0.17425.20000",
    "ExpiredBuilds": [],
    "ForkName": "LTSB2024",
    "BuildRank": 1,
    "Type": "Default",
    "UpdatedTimeUtc": "2024-02-28T23:00:07.96",
    "OfficeTenantIds": [],
    "OfficeProductNames": [],
    "OfficeCultures": [],
    "OfficeBitness": [],
    "OsVersions": [],
    "OfficePlatforms": [],
    "IsDefault": true`

`   "Id": 1170262,
    "Name": "Default",
    "Order": 100,
    "FFN": "c02d8fe6-5242-4da8-972f-82ee55e00671",
    "AvailableBuild": "16.0.17425.20000",
    "ThrottleLevel": 1000,
    "LkgBuild": "16.0.17425.20000",
    "ExpiredBuilds": [],
    "ForkName": "LTSB2024",
    "BuildRank": 1,
    "Type": "Default",
    "UpdatedTimeUtc": "2024-02-28T21:52:20.413",
    "OfficeTenantIds": [],
    "OfficeProductNames": [],
    "OfficeCultures": [],
    "OfficeBitness": [],
    "OsVersions": [],
    "OfficePlatforms": [],
    "IsDefault": true`

**Comment by CNMan** [comment]
https://github.com/CNMan/C2R/commit/eafe2bbb4b6329045168e191af0195b241c5024a
added, thanks.

**Comment by iDolmatov** [comment]
Path/files PerpetualVL202464 & PerpetualVL202486
It doesn't look like there should be a CDN from SemiAnnual there.

**Comment by CNMan** [comment]
Maybe we should wait for 2024 RTM.
